// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectBusiness;

#nullable disable

namespace ObjectBusiness.Migrations
{
    [DbContext(typeof(FBLADbContext))]
    [Migration("20251224191209_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObjectBusiness.CategoryPost", b =>
                {
                    b.Property<int>("CategoryPostId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryPostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryPostId");

                    b.ToTable("CategoryPost");

                    b.HasData(
                        new
                        {
                            CategoryPostId = 312905360,
                            CategoryPostName = "IPhone",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8399)
                        },
                        new
                        {
                            CategoryPostId = 233645044,
                            CategoryPostName = "IPad",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8404)
                        },
                        new
                        {
                            CategoryPostId = 850950744,
                            CategoryPostName = "Chromebook",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8408)
                        },
                        new
                        {
                            CategoryPostId = 2113580052,
                            CategoryPostName = "Earbuds",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8414)
                        },
                        new
                        {
                            CategoryPostId = 1278774275,
                            CategoryPostName = "Wallet",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8418)
                        },
                        new
                        {
                            CategoryPostId = 1283228775,
                            CategoryPostName = "Charger",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8423)
                        });
                });

            modelBuilder.Entity("ObjectBusiness.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundPostId")
                        .HasColumnType("int");

                    b.Property<int>("LostPostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("ObjectBusiness.Posts", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryPostId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Vector")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ObjectBusiness.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ObjectBusiness.Users", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAgreedToTerms")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickImage1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickImage2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 501221315,
                            Avatar = "avatar_CV.jpg",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 12, 8, 560, DateTimeKind.Local).AddTicks(8245),
                            DateOfBirth = new DateTime(2007, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin123@gmail.com",
                            FirstName = "Media",
                            IsActive = true,
                            IsAgreedToTerms = true,
                            LastName = "Center",
                            Password = "$2a$11$92uWViLQUKTIVIADFxhzqe39tDMoLWJX5e1FyXaeedfrq5CoMAGQ6",
                            PickImage1 = "1",
                            PickImage2 = "12",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ObjectBusiness.VerificationCode", b =>
                {
                    b.Property<int>("VerificationCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VerificationCodeId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("VerificationCode");
                });

            modelBuilder.Entity("ObjectBusiness.Posts", b =>
                {
                    b.HasOne("ObjectBusiness.CategoryPost", "CategoryPost")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ObjectBusiness.Student", b =>
                {
                    b.HasOne("ObjectBusiness.Users", "User")
                        .WithOne("Student")
                        .HasForeignKey("ObjectBusiness.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ObjectBusiness.VerificationCode", b =>
                {
                    b.HasOne("ObjectBusiness.Match", "Match")
                        .WithOne("VerificationCode")
                        .HasForeignKey("ObjectBusiness.VerificationCode", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ObjectBusiness.CategoryPost", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ObjectBusiness.Match", b =>
                {
                    b.Navigation("VerificationCode");
                });

            modelBuilder.Entity("ObjectBusiness.Users", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
